### ISSUE TITLE
Define Scope

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-Ian-arap-kirui#1]
# Description
Define scope for version 1.0 of the project.

## Requirements
- [x] Define milestones for each sprint.
- [x] Define final deliverable for v1.
- [x] DM your advisor for approval.
- [x] [Update your solo project repository `About` in GitHub](https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github).

**Comment by Ian-arap-kirui** [comment]
Sprint 1:
-Design Phase
Sprint 2: 
-Build Api 
Sprint 3: 
-Main Functionality
Sprint 4: 
-Authentication & Authorization

**Comment by Ian-arap-kirui** [comment]
Final deliverable for V1 will be an app with its main functionality being data entry and mapping it on to the dashboard
